version: "3.8"

services:
  django:
    build: .
    container_name: django
    # command: bash -c '
    #   python manage.py makemigrations
    #   && python manage.py migrate
    #   && python manage.py shell < createuser.py
    #   && python manage.py runserver 0.0.0.0:8000 '

    command: >
      sh -c "python manage.py migrate &&
            python manage.py shell < createuser.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]

    depends_on:
      - db
  db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mysql-db
      - MYSQL_USER=mysql-user
      - MYSQL_PASSWORD=mysql-password
      - MYSQL_ROOT_PASSWORD=mysql-root-password
    restart: always

volumes:
  pgdata:
