# Generated by Django 4.1.4 on 2022-12-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='actors.actor'),
        ),
    ]
