# Generated by Django 4.1.4 on 2022-12-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=300)),
                ('rank', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='directors.director')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=300)),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='movies.movie')),
            ],
        ),
    ]
