# Generated by Django 4.1.4 on 2022-12-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movies.movie'),
        ),
    ]
